### ISSUE TITLE
Paramètre obligatoire depuis la 6.0

### ISSUE THREAD

**Issue by atm-ph** [ATM-Consulting/dolibarr_module_supplierorderfromorder#25]
https://github.com/ATM-Consulting/dolibarr_module_supplierorderfromorder/blob/1ab1f980ae048e18e8209c981d9977b423b0a187/ordercustomer.php#L217

Suite à une modification => https://github.com/Dolibarr/dolibarr/commit/b62da4bb7aa669409f84aadfea3eb2116b99e5f8

Les paramètres de getEntity ont changés :
- $element est maintenant obligatoire
- $shared est maintenant à 1 par défaut au lieu de 0

Changement entre 5.0 et 6.0, du coup dans le module supplierorderfromorder il faudrait mettre "commande_fournisseur" ?

**Comment by atm-arnaud** [comment]
bien vu :+1:
