### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by rdoursenaud** [ATM-Consulting/dolibarr_module_supplierorderfromorder#7]
Le module semble mal supporter les pièces d'origines qui utilisent la même référence déclinée plusieurs fois.

Par exemple, une commande client avec :

Réf | Libellé | Description | Quantité
-----|----------|----------------|------------
P1 | Produit 1 | Le meilleur produit au monde | 1
P2 | Produit 2 | Le second meilleur produit au monde | 1
P1 | Produit 1 sur mesure | Le meilleur produit au monde en encore mieux | 1

On a 2 fois P1 mais la commande fournisseur suggérée est :

Réf | Libellé | Description | Quantité
-----|----------|----------------|-----------
P1 | Produit 1 | Le meilleur produit au monde | 1
P2 | Produit 2 | Le second meilleur produit au monde | 1

La commande devrait être identique à la pièce d'origine.

À minima on devrait avoir 2 × P1 !

**Comment by rdoursenaud** [comment]
Merci pour le correctif basique. Des chances que l'implémentation complète soit réalisée ? Avec reprise du libellé personnalisé et tout…

**Comment by atm-alexis** [comment]
Ah j'avais pas compris ça. Honnêtement ça fait trop de changement pour être fait en temps perdu. Tu veux une propale pour ça ou tu peux t'en passer ?

**Comment by rdoursenaud** [comment]
Je sais bien que ce n'est pas simple à résoudre mais c'est pile le cas d'usage de mon client. C'est pour ça que j'ai fait une demande de propale ;)
